--- # marks start of a yaml file 
- hosts: localhost # sets ansible to be run agains localhost
  connection: local
  vars:
    nvim_repo: "git@github.com:jackrmcshane/init.lua.git"
    dotfile_repo: "git@github.com:jackrmcshane/dotfiles.git"

  tasks:
    - include: tasks/common.yml
    - include: tasks/neovim.yml
