- name: install apt packages
  become: true
  apt:
    name:
      - build-essential
      - unzip
      - xorg
      - tmux
      - xclip
      - feh
      - fzf
      - ripgrep
      - python3-pip
      - screenkey
      - openssh-client # acess to remote machines
      - openssh-server # access from remote machines


- name: install c packages
  become: true
  apt:
    name:
      - cmake
      - clang
      - clang-11
      - clang-12
      - clangd
      - clangd-11
      - clangd-12

- name: install snap packages
  become: true
  snap:
    name: 
      - alacritty
      - btop
      - gh # github cli
    classic: true
