#- name: add i3-gaps ppa
#apt_repository:
#repo: 'ppa:regolith-linux/release'
#state: present
      #update_cache: yes

- name: add i3-gaps ppa
  shell:
    sudo add-apt-repository ppa:regolith-linux/release
    sudo apt update

- name: install i3-gaps
  become: true
  apt:
    name: i3-gaps

- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3-gaps'"

- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
